### ISSUE TITLE
ITVR - Update Cancel application email

### ISSUE THREAD

**Issue by airinggov** [bcgov/itvr#428]
**Title: Update the wording in the cancel application email**

**Description:** the original wording for the cancel application email was based on household applications being cancelled by the spouse or automatically by the system. The household application has been turned off so this email format is now incorrect. There is now a cancel application feature in the console that the analyst can use, this might be done at the request of the applicant. As such we need a new email format for these cancelled applications. If household applications are ever enabled again we may need to distinguish these 2 different cancel scenarios.

**Wireframe:** na

**Purpose and benefit to user:** the current email is confusing and incorrect, the new email wording will make more sense to the applicant

**Acceptance Criteria:**

- [ ] Given I am an individual applicant, When my application is cancelled, then i get an email with the appropriate wording
- [ ] Given I am a household applicant, When my application is cancelled, then I get an email with different wording 

**Development Checklist:**
- [ ] Write the two cancellation emails 
- [ ] comment out the household email because currently household applications are not allowed
- [ ] make sure that the individual's email sends when an idir user cancels the application

**Notes:** new email wording

Your application has been cancelled.

If you haven’t yet received a rebate you are encouraged to apply again.

If you think this was done in error or you have questions, please feel free to contact us at ZEVPrograms@gov.bc.ca

**Comment by emi-hi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/428?planning-poker) with Zenhub @AlexZorkin @tim738745

**Comment by emi-hi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/428?planning-poker) with Zenhub @vibhiquartech

**Comment by emi-hi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/428?planning-poker) with Zenhub @JulianForeman

**Comment by emi-hi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/428?planning-poker) with Zenhub @jig-patel

**Comment by emi-hi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/428?planning-poker) with Zenhub @emi-hi
