### ISSUE TITLE
ITVR - Console utility to update DL#

### ISSUE THREAD

**Issue by airinggov** [bcgov/itvr#430]
New utility in Console to change the DL# if an applicant enters it wrong

**Description:** 
Build a new component where an IDIR user can update the DL#. This could be done so that a record of the original DL# is retained, but only as a record, so that the DL# could be released in case it belongs to someone else. 
Need to consider keeping a record of the changes made so that gov users can trace back any changes made to DL#'s

**Wireframe:** Al to add something?

**Purpose and benefit to user:**
This has been a reoccurring issue that so far has been made as a direct data fix in the DB by a developer. This will allow the ITVR Business Admin the capability to update a DL# directly in the console.

**Acceptance Criteria:**

- [ ] Given I am a ITVR Business Admin, When I am logged into the ITVR console, then I can search for a rebate by DL# or application ID # and update and save the DL#

**Development Checklist:**
- [ ] Create history table for storing old drivers licences
- [ ] Add function that will save old drivers license to new history table when updating the record
- [ ] Add that functionality to the console with an editable text box, so idir users can change the drivers license number and then save it. Do it the same way that Cancel Application is done but make sure that it adds to the history table. 

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/430?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech

**Comment by jdon-zev** [comment]
Two comments:
- It would have been good to allow letters to be used when editing the DL# (e.g. for the person with no license)
- It would be better if you could access the history of changes tot he DL# form the main application. Or they were linked in some more intuitive way.
