### ISSUE TITLE
ITVR - Reducing DL# errors

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/itvr#439]
**Description:**
The ITVR business area is finding a consistent number of errors when people enter their DL# in the rebate approval application form. We want to try to minimise these errors.

Suggestion to reduce errors are:
- Add text to the page to ask people to take care entering their DL# 

**Wireframe:** 
https://preview.uxpin.com/7f6104a26108508bb185e1b602677a5f91f49724#/pages/152776163?mode=fm

**Purpose and benefit to user:**
Accuracy of DL# number is very important as the rebate applicant can be denied their rebate at the dealership if their DL# does not match the DL# in their approval.

**Acceptance Criteria:**

- [ ] Given I am a rebate applicant, I want to ensure I am entering the correct DL# in my application form.

**Development Checklist:**
- [ ] Add the new text to the application form, as displayed in the wireframe.

new text

BC Driver's Licence number (You will present your licence at the new car dealership to redeem your rebate. Please ensure this number matches your licence otherwise you will not be able to claim your rebate):

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/439?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/439?planning-poker) with Zenhub @vibhiquartech

**Comment by airinggov** [comment]
Nick has approved this new text
