### ISSUE TITLE
ITVR - DL# corrections and rebate cancellation: database changes

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/itvr#460]
Describe the task

**Task 1**
Cancel the following pre-ITVR application. They never received their original rebate as the ZEV purchase was cancelled. Delete from the database so the person is able to apply again.

**Task 2**
The attached file has the latest request from NCDA to change DL#'s in the ITVR database. Please replace the 10 old DL#'s with the new ones as shown in the highlighted yellow rows of the attached spreadsheet.

The business area reached out directly to these applicants to confirm their DL#. All of them have sent in a DL photo and we’ve confirmed the information on there with their applications.
 See Teams for spreadsheet

Purpose
1. The person didn't receive their vehicle rebate so they should still be eligible to apply for a rebate in the ITVR system.
2. The DL# submitted with their rebate approval request was incorrect. In order to ensure we hold the correct DL# that has received a rebate the DL#'s needed to be updated in our database.

**Acceptance Criteria**
1. The indivudal is able to apply for a rebate approval.
2. The DL#'s are corrected according to the attached spreadsheet.

**Development Checklist**
(1) Go into the database directly and make these changes.
(2) Optionally, can wait until the console utility to edit DL#'s (#430) is live in production, and have an analyst make the changes themselves for no.2.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/460?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech

**Comment by tim738745** [comment]
@jdon-zev I did task 1 (deleting the pre-itvr application). Can we do an itvr prod deployment so that the console users can change those DL#s themselves?

**Comment by jdon-zev** [comment]
@tim738745 Yes, I spoke to Kuan and we will do a prod release tomorrow.
