### ISSUE TITLE
ITVR - Add rebate application number to API for NCDA

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/itvr#462]
**Description:**
The NCDA are finding it difficult to locate rebate applications based solely on drivers license number. To help we would like to add the application number to the data sent to NCDA via the API.

**Purpose and benefit to user:**
The NCDA will be better able to locate specific rebate applications.

**Acceptance Criteria:**
The NCDA receive application numbers for approved rebate application form the ITVR system along with the other information on drivers license number and rebate approval amount..
The NCDA can search for approved rebate applications using the application number.

- [ ] Given I am someone working for the NCDA, When I am trying to locate a rebate application. then I would like to be able to search the NCDA system  using rebate application numbers.

**Development Checklist:**
- [ ] Check to see that the NCDA API accepts this new field when posting information over to them (can use postman)
- [ ] In ncda.py, make changes to the notify() function to add the application id to the payload.

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/462?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech

**Comment by tim738745** [comment]
Heard back from NCDA; can now post over rebates with application ID (can also post over rebates with no application id; that still works).

**Comment by tim738745** [comment]
Note: part of PR for issue 477 (the second commit)

**Comment by jdon-zev** [comment]
Released to production - Tim to monitor for issues.
