### ISSUE TITLE
ITVR - Applicant date of birth being automatically changed

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/itvr#463]
**Describe the Bug**
A member of the public is trying to make a rebate application and the information they entered for their date of birth is not displayed as the same value they entered after they submit the application. 

Examples is app no. #Xj3rnKVLQ4XLfAok (Chin Pui Li)

Note: The analysts have no way to correct the date of birth in the console. They have rejected one application and asked the applicant to re-submit but they experienced the same problem.

This may be a specific user issue but I'd like to:
- Check this is not a potential issue for other users

**Expected Behaviour**
When applicant enters their date of birth it should not change in any way form the information they entered.

**Actual Behaviour**
When the applicant enters the number 18 for the day of their birth it automatically shifts to 19, one day ahead.

**Implications**
Applicants cannot correctly enter their dates of birth

**Acceptance Criteria**
- [ ] When a user enters their date of birth and submits the application it should correctly save the date entered.

**Developer Checklist**
- [ ] Double check this hasn't occurred on other applications as well.
- [ ] Research if this is a user input error or if this is a timezone/date issue on our backend.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/463?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech
