### ISSUE TITLE
ITVR - Allow console users to use letters when changing applicant DL numbers

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/itvr#469]
**Describe the task**
Card 430 was completed allowing ITVR console users to change applicant driver license numbers. However it is only possible to change the number to another number. Only numerical characters are accepted in the console.
The business area would like to be able to use letters and numbers in some instances, such as for the applicant who is blind and therefore does not have a DL number.

**Purpose**
This allows console users to create unique 'DL#s' for applicant that do not have a a real DL#. Using only numbers runs the risk that we use someone else's actual DL#.

**Acceptance Criteria**
- Console user are able to enter both letters and numbers in the DL# field when editing a DL#.

**Developer Checklist**
(1) The developer who implemented this feature actually went out of their way to prevent console users from entering DL#s containing anything but numbers! So all that needs to be done is to remove that frontend check, and to check that the NCDA's sharepoint API will accept DL#s with letters in it.

**Comment by airinggov** [comment]
button to save is disabled if I enter a letter

**Comment by tim738745** [comment]
@airinggov it has to be an uppercase letter I think

**Comment by airinggov** [comment]
@tim738745 ah right, that works, thanks Tim
