### ISSUE TITLE
ITVR -  getting redeemed rebates from the NCDA

### ISSUE THREAD

**Issue by tim738745** [bcgov/itvr#477]
**Describe the Bug**
The issue is that the GET requests we’re sending to the sharepoint API to get redeemed rebates is giving us this error:
 
{
    "error": {
        "code": "-2147024860, Microsoft.SharePoint.SPQueryThrottledException",
        "message": {
            "lang": "en-US",
            "value": "The attempted operation is prohibited because it exceeds the list view threshold."
        }
    }
}
 
Our GET requests look like:
 
https://newcardealers.sharepoint.com/sites/ElectricVehicleRebateApplications/_api/web/lists/getbytitle('ITVREligibility')/items?$select=Id,Title,Modified,Status&$filter=(Status eq 'Redeemed')and(Modified ge datetime'2023-03-28T00:00:00Z')&$top=1000
 
We execute this request every night at 10pm, and on March 14th, it stopped working. The error message mentions exceeding the list view threshold, but since this request is executed daily with an incremented “Modified” date, it should return only a minimal number of records each time it’s run (off the top of my head, I think it was less than 50 each day when it was working). The request also includes the “top” parameter, which we’ve set equal to 1000; I’ve tried running this request with “top” equal to a smaller number (such as 10), but I got the same error.
 
Also, we’re still successfully POSTing information over via the sharepoint API, and we use the same client id/secret for that as we do for our GET requests.

**Expected Behaviour**
The request should be successful and return the redeemed rebates.

**Actual Behaviour**
The request fails with status 500.

**Implications**
Once this is fixed, we'll need to re-run the request from March 14 (the first day the request failed) so that we get all the redeemed rebates from that point forth (can do this in the admin console). Otherwise, rebates flagged as redeemed during the period this request is not working won't be reflected as such in our system.

**Steps To Reproduce**
This request is sent by a job each night at 10pm, but you can reproduce it using postman.

**Development Requirements**
- [ ] Investigate cause of the server error and create an api request that successfully returns data
- [ ] Implement fix for our automated api call 
- [ ] Re-run get request with starting date of March 14th 2023 to current date, in order to sync out of date data

**Comment by tim738745** [comment]
Contacted NCDA/Elantis on March 29, 2023; waiting to hear back

**Comment by tim738745** [comment]
Heard back from NCDA; they suggested rearranging the order of the filters and that seems to work (used postman to test). So changing the order will work for requests going forward, but the issue is all the redeemed rebates we missed since March 14; re-running the job from that day may work but it is dependent on how many rebates have been sent to them/how many have been redeemed since that date; if it's more than 5000, the request will still fail. Can create a run-once job that doesn't use any filters and makes iterative requests to grab all rebates we've sent to them so far and filter on our end to identify and flag rebates redeemed from March 14 onwards.

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/477?planning-poker) with Zenhub @emi-hi @tim738745 @JulianForeman @jig-patel

**Comment by jdon-zev** [comment]
Released to production - Tim to monitor for issues.
