### ISSUE TITLE
ITVR - change to DL#'s pre-income testing

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/itvr#481]
**Describe the task**
NCDA has a few DL# change requests that the business area are unable to make. They would like us to make the following changes. 

1.	Delete preITVR application FStfnGpcZB5iuaFu. Applicant applied via income testing using incorrect DL#, and dealer applied for grandparented rebate under correct DL#. Need to delete the grandparented rebate so they can then change the ITVR rebate DL to the correct number. 
2.	Delete preITVR application Zs2yodGUWV7dmnHE as they did not receive the rebate, their spouse received an income-tested rebate. 
3.	Delete preITVR application FWPrwApRTuDqCF29 as the applicant actually received a rebate under their business so they are still eligible to apply as an individual.
4.	Add an application/ban a DL# from applying. Someone received a rebate under their business but the vehicle was actually in their personal name so they are not eligible to apply for an individual rebate (DL# 5499026) and we want to make sure they cannot apply again. 

**Purpose**
To correct the record of rebate's received to allow these individual to be eligible/ineligible to apply for an income tested rebate.

**Acceptance Criteria**
- Certain DL#s should be allowed to apply, others should not (see description above)

**Development Checklist**
(1) Connect to the prod DB, and make the changes as described above. For task #4 above, just add a new is_legacy = True application entry with the DL# to the go_electric_rebate_application table

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/481?planning-poker) with Zenhub @emi-hi @jig-patel @JulianForeman @tim738745

**Comment by jdon-zev** [comment]
Changes made direct to prod db - can't be user tested.
