### ISSUE TITLE
ITVR - rebates mismatch

### ISSUE THREAD

**Issue by tim738745** [bcgov/itvr#489]
**Describe the task**
At the time of this writing, we have 13545 rebates in our system, but the NCDA has 13558 rebates, a difference of 13. This difference could be caused by the fact that when a console user cancels an approved rebate, they have to tell the NCDA which one they cancelled and then the NCDA has to manually delete it on their end; it could be the case that perhaps, occasionally, someone forgets to delete it. It could also be caused by the fact that some of the rebates on the NCDA side are test rebates that were not deleted. So, the task is to put the number of rebates in sync, and to keep them in sync.

**Purpose**
If the rebates are not in sync, we could encounter a case where an applicant applies successfully on our end, but when we try to send their DL# to the NCDA, we get an error that says we already sent that DL# to them.

**Acceptance Criteria**
- [ ] When a console user cancels an approved application, the system automatically deletes the associated rebate on the NCDA's end, if one exists.
- [ ] Write a script that identifies which rebates are the "extraneous" ones on the NCDA's end, and delete those.

**Additional context**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/489?planning-poker) with Zenhub @AlexZorkin @jig-patel @JulianForeman @tim738745

**Comment by jdon-zev** [comment]
This card is not something that can be user tested. Card to be closed following agreement with the devs.
