### ISSUE TITLE
ITVR - error logs

### ISSUE THREAD

**Issue by tim738745** [bcgov/itvr#563]
**Describe the task**
If an applicant enters an invalid email when applying, this will cause 422 errors when we ask CHES to send them an email using that email address. In the logs, this will be displayed (most likely multiple times due to retries). The task is to clean up the logged error messages, and document this behaviour.

**Purpose**
This will make it more clear what's happening to whoever looks at the logs

**Acceptance Criteria**
- [ ] See if we can customize Django Q's way of logging these scenarios, and if so, customize it appropriately.
- [ ] Write documentation about this and put it in the README/developer's guide.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/563?planning-poker) with Zenhub @AlexZorkin @tim738745
