### ISSUE TITLE
ITVR - delete go_electric_rebate when expiring a rebate

### ISSUE THREAD

**Issue by tim738745** [bcgov/itvr#577]
**Describe the task**
When expiring a rebate, delete the associated entry in the go_electric_rebate table

**Purpose**
If we don't do this, it could lead to an error when an analyst uploads the CRA file due to the uniqueness constraint on DL#s in the go_electric_table

**Acceptance Criteria**
- [ ] When a rebate gets expired, the associated entry in the go_electric_rebate table gets deleted.

**Additional context**
This should be done and in production before August 23rd, 2023, which is the earliest expiration date that exists in our system.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/577?planning-poker) with Zenhub @AlexZorkin @tim738745
