### ISSUE TITLE
ITVR - Application form error check DL#

### ISSUE THREAD

**Issue by airinggov** [bcgov/itvr#593]
**Description:** BC driver's licence numbers are being changed from 7 to 8 digits. 7 digit numbers when renewed will be reissued as 8 digit numbers with a leading zero.

We need to add an error check to prevent a rebate being issued to a 7 digit DL and the same licence number with a leading zero. These would need to be identified as duplicate and prevent form submission.

**Wireframe:** <link>

**Purpose and benefit to user:** this will prevent people from getting 2 rebates and breaking program rules

**Acceptance Criteria:**

- [ ] Given I am a rebate applicant, When I am submitting the online application form, then I am prevented from submitting the form twice with a 7 digit licence number and the same number with a leading zero 

**Development Checklist:**
- [ ] Implement this check in the frontend, and see if it's possible to implement an associated database constraint as well (and if so, please do so).
- [ ] Check to see if the existing production data has these DL# cases (dump the the production data write a script to do this).

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/593?planning-poker) with Zenhub @JulianForeman @tim738745
