### ISSUE TITLE
ITVR - Update Expiry email wording

### ISSUE THREAD

**Issue by airinggov** [bcgov/itvr#595]
**Title:** Update Expiry email wording

**Description:** The email requires more detailed information about reapplying for a rebate.

**Wireframe:** <link> email wording:

E-mail confirmation of application being expired by system TO: Applicant 
From: zevprogramsdonotreply@gov.bc.ca 
Subject: CleanBC Go Electric – Application #XXXX – Expired 
This email was generated by the CleanBC Go Electric Passenger Vehicle Rebate program application.   
You are receiving this email as it has been one year since you were approved for a Passenger Vehicle Rebate. Your rebate approval has expired. 
You can reapply for another rebate approval 15 days from today. If you want to reapply within the next 15 days, please contact ZEVPrograms@gov.bc.ca
https://goelectricbc.gov.bc.ca/ 
Please note that rebates are available until the program funds are exhausted.  
Questions? 
Please feel free to contact us at ZEVPrograms@gov.bc.ca 

**Purpose and benefit to user:** If they reapply within 15 days of expiry the user will receive an error that they already have a rebate.

**Acceptance Criteria:**

- [ ] Given I am a rebate applicant, When my rebate expires and I receive an email it instructs me on how I can reapply.

**Development Checklist:**
- [ ] Change the expiry email wording in tasks.py

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/595?planning-poker) with Zenhub @JulianForeman @tim738745

**Comment by shayjeff** [comment]
This card has been approved today by the programs manager and is now ready for production.
