### ISSUE TITLE
ITVR - Create new email alert 2 weeks before rebate expiry

### ISSUE THREAD

**Issue by airinggov** [bcgov/itvr#596]
**Title:** Create a new email alert 2 weeks before rebate expiry

**Description:** This will provide a rebate applicant a 2 week warning to use their rebate.

**Wireframe:** <link> email wording:

2 week alert E-mail of application being expired by system TO: Applicant 
From: zevprogramsdonotreply@gov.bc.ca 
Subject: CleanBC Go Electric – Application #XXXX – Will expire in 2 weeks 
This email was generated by the CleanBC Go Electric Passenger Vehicle Rebate program application.   
You are receiving this email as it has nearly been one year since you were approved for a Passenger Vehicle Rebate. Your rebate approval will expire in 2 weeks. 
If you do not purchase an EV and receive a rebate within the next 2 weeks, you will need to apply for a new rebate approval on the program website: 
https://goelectricbc.gov.bc.ca/ 
Please note that rebates are available until the program funds are exhausted.  
Questions? 
Please feel free to contact us at ZEVPrograms@gov.bc.ca 

**Purpose and benefit to user:** People with rebate approvals will get notified to use their rebate before they expire.

**Acceptance Criteria:**

- [ ] Given I am a rebate approval recipient, When my approval is about to expire, then I will get an email

**Notes:**
(1) will need to create a new job (or 2 separate jobs (doesn't matter)) that sends out the warning emails and expiry emails based on those fields (among other things).

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/596?planning-poker) with Zenhub @tim738745

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/596?planning-poker) with Zenhub @JulianForeman

**Comment by shayjeff** [comment]
This card has been approved today by the programs manager and is now ready for production.
