### ISSUE TITLE
ITVR - Task: ITVR- Driver's License Verification Feature 

### ISSUE THREAD

**Issue by shayjeff** [bcgov/itvr#620]
**Describe the Task:**
Create a verification feature in the ITVR system to restrict applicants from submitting forms with an 8-digit driver's license number that doesn't start with 0 or 3.

**Purpose:**
This task is necessary to fulfill the NCDA's request received by the business area.  The goal is to prevent applicants from using incorrect driver's license numbers, ensuring data accuracy, and aligning with NCDA requirements.

**Acceptance Criteria:**
- [ ] The ITVR system should reject or flag submissions if the driver's license number is 8 digits long and doesn't start with a 0 or 3; otherwise, the submission is rejected or flagged.

**Development Checklist**

**Additional Context:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/620?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745

**Comment by kcabhar** [comment]
Waiting to hear back from BA on how many digits ICBC wants - BA is waiting on NCDA to get back to them

**Comment by shayjeff** [comment]
Update - (2024-04-19) from BA - waiting to hear from ICBC. I'm moving this card to the ITVR backlog until we receive the information needed to proceed.

**Comment by shayjeff** [comment]
Tested
