### ISSUE TITLE
ITVR - Changes to Auto Response Email

### ISSUE THREAD

**Issue by shayjeff** [bcgov/itvr#639]
**Title:** 
Requested changes to auto response email (ITVR)

**Description:** 
The program team has requested to revise the wording in the email notification sent to applicants upon submission of their rebate applications under the CleanBC Go Electric Passenger Vehicle Rebate program (ITVR). See the new wording in the note section. 

**Wireframe:** <link>

**Purpose and benefit to user:**
The purpose of this change is to provide applicants with clearer information about the status of their rebate application submissions, expectations regarding response times, and guidance on contacting the program office. 

**Acceptance Criteria:**

- [ ] Given I am an applicant, When I submit my rebate application, then I receive a confirmation email with revised wording that includes information about the expected response time and guidance on contacting the program office.
- [ ] Given I am an applicant, When I receive the confirmation email, then it includes a reminder not to inquire about application status before 3 weeks and to check junk/spam folders for missed emails.

**Development Checklist:**
- [ ] In tasks.py, update the wording of the email in question.

**Notes:**
The team discussed the phrasing of the automatic email that gets sent to applicants after they submit their rebate applications. We would like to include more language in the hopes of reducing the number of emails relating to application statuses. See below.

-------
New wordings:

This email was generated by the CleanBC Go Electric Passenger Vehicle Rebate program application. Thank you.

We have received your application for a rebate under the CleanBC Go Electric Passenger Vehicle Rebate program. You can expect to get an email reply with the result of your application within 3 weeks. We are unable to speed up the application process as our screening is automated. 

Please keep this e-mail for your records.

Questions? Please feel free to contact us at ZEVPrograms@gov.bc.ca. **Emails asking about the status of your application will not be responded if it has not been 3 weeks since your application was submitted**. Please check your junk/spam folder for any missed emails.

----------
Please go ahead and change the auto response wordings (keep the bolded sentence in bold)– if you have questions don’t hesitate to reach out.

-----------
Current wordings:
This email was generated by the CleanBC Go Electric Passenger Vehicle Rebate program application. 
Thank you.

We have received your application for a rebate under the CleanBC Go Electric Passenger Vehicle Rebate program. You can expect to get an email reply with the result of your application within 3 weeks. 

Please keep this e-mail for your records.

Questions?

Please feel free to contact us at ZEVPrograms@gov.bc.ca

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/639?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745

**Comment by shayjeff** [comment]
Tested - email response is exactly as requested.
