### ISSUE TITLE
ITVR - deploy spring service for cra file encryption/decryption

### ISSUE THREAD

**Issue by tim738745** [bcgov/itvr#662]
**Describe the task**
Deploy this: https://github.com/bcgov/itvr/pull/640

**Purpose**
This automates, to an extent, the encryption/decryption of CRA files

**Acceptance Criteria**
- [ ] The code contained in https://github.com/bcgov/itvr/pull/640 is deployed successfully to production.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/662?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745
