### ISSUE TITLE
ITVR - Update Consent Statement 

### ISSUE THREAD

**Issue by shayjeff** [bcgov/itvr#664]
**Describe the task:**  
Remove mention of spouse from the consent statement in the BCeID application form. Additionally, check if there is a similar statement in the BC Services card application.

**Purpose:**  
The purpose of this task is to update the consent statement in the BCeID application form to remove references to spouses for clarity and accuracy in the application process and to reflect updated requirements. 

**Acceptance Criteria:**
- [x] Remove mention of spouse from the consent statement in the BCeID application form.
- [ ] Confirm if a similar statement exists in the BC Services card application to find out whether it requires similar amendments for consistency.

**Additional context:**
Original Request from the Programs Team: The consent statement for BCeID applicants still includes mention of spouse (from when household applications were available). Please remove mention of spouse. Can you also check if there is a similar statement in the BC Services card app? https://electric-vehicle-rebates.gov.bc.ca/form
<img width="898" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlJtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e73abf4bf84240613ea2e03ec02026ef6e62fcb9/image.png" alt="image.png" />

New Text:
 
4 - Any misinformation or errors in information can result in the Ministry of Energy, Mines and Low Carbon Innovation and any other ministry, agency or contractor of the Government of British Columbia requiring the return of the money I received, which will be due and payable upon demand.

6 - I agree that any information about me that is or has been obtained by the British Columbia Ministry of Energy, Mines and Low Carbon Innovation for purposes of administering the CleanBC Go Electric Vehicle Rebate Program, or any information that is prepared from that information, may be provided to and used by any person employed in the service of, occupying a position of responsibility in the service of, or engaged by or on behalf of, the government of British Columbia for the purposes of research, the formulation or evaluation of fiscal policy, processing this application, verifying or investigating information related to this application, and/or the collection of any money that becomes due by me to the government of British Columbia as a result of incorrect information provided in this application. I also agree that information about me that I provide to any person referred to above may be provided to any other person referred to above and used for these same purposes.

**Comment by airinggov** [comment]
Potential new text to 4 and 6 on both BCeID and BCSC forms:

4. Any misinformation or errors in information can result in the Ministry of Energy, Mines and Low Carbon Innovation and any other ministry, agency or contractor of the Government of British Columbia requiring the return of the money I received, which will be due and payable upon demand.
6. I agree that any information about me that is or has been obtained by the British Columbia Ministry of Energy, Mines and Low Carbon Innovation for purposes of administering the CleanBC Go Electric Vehicle Rebate Program, or any information that is prepared from that information, may be provided to and used by any person employed in the service of, occupying a position of responsibility in the service of, or engaged by or on behalf of, the government of British Columbia for the purposes of research, the formulation or evaluation of fiscal policy, processing this application, verifying or investigating information related to this application, and/or the collection of any money that becomes due by me to the government of British Columbia as a result of incorrect information provided in this application. I also agree that information about me that I provide to any person referred to above may be provided to any other person referred to above and used for these same purposes.

**Comment by shayjeff** [comment]
New text changes have been approved by the business area on April 16th.  
"Hi Shaylene, We agree with the below change."

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/664?planning-poker) with Zenhub @emi-hi @tim738745
