### ISSUE TITLE
ITVR Task - Add Feature: Legacy Application Deletion

### ISSUE THREAD

**Issue by shayjeff** [bcgov/itvr#693]
**Describe the task**
Create a feature to enable the deletion of legacy applications based on the presence of the "is_legacy" flag in the system.
**Purpose**
Allow the business area to independently manage legacy application deletions, reducing reliance on the development team. This streamlines, the process for handling requests related to legacy applications.

**Acceptance Criteria**
- [ ] Users with appropriate permissions can access the delete functionality.
- [ ] Only applications marked as legacy (with the "is_legacy" flag) can be deleted.
- [ ] A confirmation prompt is displayed before deletion to prevent accidental deletions.

**Development Checklist**
(1) Make a new proxy model and ModelAdmin class (see admin.py) that gets the legacy applications, and implement the delete functionality; we'll probably also need additional HTML templates (see api/templates)

**Additional context**
-  Consider providing training to the business area to familiarize them with the new deletion feature and its usage.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/itvr/693?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745
