### ISSUE TITLE
ITVR - fix rebate amount typo

### ISSUE THREAD

**Issue by tim738745** [bcgov/itvr#717]
**Describe the Bug**
The ZEV_MID rebate amount that goes out in the approval emails should be 2668, not 2688.

**Expected Behaviour**
The ZEV_MID rebate amount that goes out in the approval emails should be 2668.

**Actual Behaviour**
The ZEV_MID rebate amount that goes out in the approval emails is 2688.

**Implications**
This is incorrect

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: End-user
1. Apply for a rebate
2. Get approved
3. See email with incorrect number

**Comment by shayjeff** [comment]
Tested - PO and BA reviewed the email and everything looks as should.
